/* Generated by           cobc 3.2.0 */
/* Generated from         E:\msys64\home\PC\COBOL\calles\atm.cbl */
/* Generated at           Jun 30 2025 21:01:24 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        E:\msys64\mingw64\bin\cobc.exe -x -I E:\msys64\home\PC\COBOL\calles\includes -g -fmf -o atm.exe E:\msys64\home\PC\COBOL\calles\atm.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

#define cob_nop	if (!module) cob_nop

